const foods = [
  {
    id: '1',
    name: 'Meat Pizza',
    category:'Pizza',
    ingredients: 'Mixed Pizza',
    price: '8.30',
    description : 'Meat pizza is a delicious option that features an assortment of savory meats as toppings, such as pepperoni, sausage, and bacon. These flavorful meats add depth and richness to the pizza, creating a satisfying and indulgent meal. Meat lovers often gravitate towards this classic pizza choice for its hearty and satisfying taste.',
    image: require('../assets/meatPizza.png'),
  },
  {
    id: '2',
    name: 'Cheese Pizza',
    category:'Pizza',
    ingredients: 'Cheese Pizza',
    price: '7.10',
    description:'Cheese pizza, also known as margherita pizza, is a simple yet beloved classic. It typically consists of a crust topped with tomato sauce and generous amounts of melted cheese, usually mozzarella. The gooey, stretchy cheese melds with the tangy tomato sauce to create a comforting and flavorful combination that appeals to pizza lovers of all ages.',
    image: require('../assets/cheesePizza.png'),
  },
  {
    id: '3',
    name: 'Chicken Burger',
    category:'Burger',
    ingredients: 'Fried Chicken',
    price: '5.10',
    description:'A chicken burger is a popular alternative to beef burgers, featuring a grilled or fried chicken patty as the main ingredient. The chicken patty is often seasoned with herbs and spices to enhance its flavor and may be accompanied by various toppings such as lettuce, tomato, onions, and cheese. Chicken burgers offer a lighter and healthier option compared to traditional beef burgers while still providing a satisfying and delicious meal for burger enthusiasts.',
    image: require('../assets/chickenBurger.png'),
  },
  {
    id: '4',
    name: 'Sushi Makizushi',
    category:'Sushi',
    ingredients: 'Salmon Meat',
    price: '9.55',
    description:'Sushi is a traditional Japanese dish consisting of vinegared rice combined with various ingredients, such as seafood, vegetables, and sometimes tropical fruits. These ingredients are often wrapped in seaweed, known as nori, and served in bite-sized portions. Sushi is renowned for its delicate flavors, artistic presentation, and the meticulous craftsmanship involved in its preparation, making it a favorite choice for both casual meals and special occasions worldwide.',
    image: require('../assets/sushiMakizushi.png'),
  },
  {
    id: '5',
    name: 'Salada Legumes',
    category:'Salad',
    ingredients: 'Mixed Veggies',
    price: '4.15',
    description:'Salad is a versatile dish made primarily from fresh vegetables, often mixed with fruits, nuts, seeds, or grains, and dressed with vinaigrettes, dressings, or sauces. It is typically served cold as a refreshing appetizer, side dish, or main course. Salads come in various forms, from simple green salads to more elaborate creations incorporating proteins like grilled chicken or shrimp, catering to a wide range of tastes and dietary preferences. They are valued for their nutritional content, vibrant colors, and the opportunity to showcase seasonal produce.',
    image: require('../assets/salad3.png'),
  },
  {
    id: '6',
    name: 'Napoli Pizza',
    category:'Pizza',
    ingredients: 'Mixed Veggies',
    price: '10.25',
    description:'Napoli pizza, or Neapolitan pizza, originates from Naples, Italy, and is known for its simple yet delicious toppings and thin, soft crust. It is traditionally topped with San Marzano tomatoes, mozzarella cheese made from buffalo milk, fresh basil leaves, and extra virgin olive oil. Napoli pizza is baked quickly in a wood-fired oven at a high temperature, resulting in a soft and chewy crust with charred spots, and is often enjoyed as a classic and authentic Italian dish around the world.',
    image: require('../assets/pizza2.png'),
  },
];

export default foods;
